import type { LoaderFunctionArgs, ActionFunctionArgs } from "react-router";
import { useEffect, useState } from "react";
import { useLoaderData, useFetcher, useSearchParams } from "react-router";
import { INSTALL_TRIAL_DAYS } from "../lib/plan.constants";
import { Icon } from "../components/ui/Icon";
import { Button } from "../components/ui/Button";
import { Badge } from "../components/ui/Badge";
import { Card } from "../components/ui/Card";
import { Segmented } from "../components/ui/Segmented";
import { useToast } from "../components/ui/Toast";
import { ConfirmDialog } from "../components/ui/ConfirmDialog";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const [
    { requireShop },
    { getBillingAccess },
    { syncShopifySubscriptions },
    { default: prisma },
  ] = await Promise.all([
    import("../lib/shop.server"),
    import("../lib/plan.server"),
    import("../lib/billing.server"),
    import("../db.server"),
  ]);
  const { admin, shop } = await requireShop(request);

  await syncShopifySubscriptions({
    admin: admin as never as { graphql: AdminGraphqlClientArg },
    shopId: shop.id,
  });
  const syncedShop = await prisma.shop.findUnique({
    where: { id: shop.id },
    include: { activeSubscription: { include: { plan: true } } },
  });

  const effectiveShop = syncedShop ?? shop;
  const access = await getBillingAccess(effectiveShop);
  const plans = await prisma.plan.findMany({ orderBy: { priceMonthly: "asc" } });
  return {
    plans: plans.map(p => ({
      id: p.id,
      name: p.name,
      priceMonthly: p.priceMonthly / 100,
      priceAnnual:  p.priceAnnual  / 100,
      annualTotal: (p.priceAnnual / 100) * 12,
      trialDays: p.trialDays,
      qrCodeLimit: p.qrCodeLimit,
      campaignLimit: p.campaignLimit,
      historyDays: p.historyDays,
      attribution: p.attribution,
      integrations: p.integrations,
      multiStore: p.multiStore,
      api: p.api,
      customDomain: p.customDomain,
      prioritySupport: p.prioritySupport,
    })),
    currentPlanId: access.plan.id,
    currentCycle: access.cycle,
    accessStatus: access.status,
    trialDaysLeft: access.daysLeft,
    trialEndsAt: access.trialEndsAt,
    hasActiveSubscription: access.status === "active",
  };
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const [
    { requireShop },
    { startSubscription, cancelSubscription },
    { default: prisma },
  ] = await Promise.all([
    import("../lib/shop.server"),
    import("../lib/billing.server"),
    import("../db.server"),
  ]);
  const { admin, shop } = await requireShop(request);
  const form = await request.formData();
  const intent = String(form.get("intent") ?? "");

  if (intent === "subscribe") {
    const planId = String(form.get("planId") ?? "");
    const cycle  = (String(form.get("cycle") ?? "MONTHLY").toUpperCase() === "ANNUAL" ? "ANNUAL" : "MONTHLY") as "MONTHLY" | "ANNUAL";
    const plan = await prisma.plan.findUnique({ where: { id: planId } });
    if (!plan) return { ok: false, error: "unknown-plan" } as const;
    const url = new URL(request.url);
    const host = (form.get("host") as string | null) || url.searchParams.get("host");
    const appUrl = process.env.SHOPIFY_APP_URL ?? url.origin;
    try {
      const { confirmationUrl } = await startSubscription({
        admin: admin as never as { graphql: AdminGraphqlClientArg },
        shop,
        plan,
        cycle,
        appUrl,
        host,
        trialDays: 0,
      });
      return { ok: true, intent, confirmationUrl } as const;
    } catch (err) {
      return {
        ok: false,
        intent,
        error: "billing-checkout",
        message: err instanceof Error ? err.message : "Shopify billing checkout failed.",
      } as const;
    }
  }

  if (intent === "cancel") {
    const active = shop.activeSubscription;
    try {
      if (active) {
        await cancelSubscription({
          admin: admin as never as { graphql: AdminGraphqlClientArg },
          subscription: active,
        });
      }
      return { ok: true, intent } as const;
    } catch (err) {
      return {
        ok: false,
        intent,
        error: "billing-cancel",
        message: err instanceof Error ? err.message : "Shopify billing cancellation failed.",
      } as const;
    }
  }

  return { ok: false, error: "unknown-intent" } as const;
};

type AdminGraphqlClientArg = (q: string, options?: { variables?: Record<string, unknown> }) => Promise<{ json: <T>() => Promise<T> }>;

const PLAN_META: Record<string, { icon: string; accent: string; tagline: string; featured?: boolean; badge?: string }> = {
  starter: { icon: "rocket",    accent: "blue",   tagline: "Launch your first QR codes and campaign pages." },
  growth:  { icon: "zap",       accent: "violet", tagline: "Measure sales generated by every scan.", featured: true, badge: "Most popular" },
  pro:     { icon: "sparkles",  accent: "amber",  tagline: "For high-volume campaigns and advanced teams." },
};

const PLAN_ORDER = ["starter", "growth", "pro"];

const FAQS = [
  { q: "Can I change plans later?", a: "Yes. You can upgrade or downgrade at any time. Shopify handles billing adjustments when the subscription changes." },
  { q: "What happens if I downgrade?", a: "Your existing QR codes and campaigns remain available. If you exceed the new plan limit, creating or duplicating new items is blocked until you archive items or upgrade again." },
  { q: "How does the free trial work?", a: `The ${INSTALL_TRIAL_DAYS}-day free trial starts when the app is installed and gives access to Pro features. It is not restarted by subscribing, cancelling, or reinstalling.` },
  { q: "Are taxes included?", a: "Displayed prices exclude taxes. Shopify adds applicable taxes during checkout based on the store's billing location." },
  { q: "What happens when the trial ends?", a: "If there is no active subscription after the installation trial, the app redirects to Pricing and active QR codes/campaigns are paused until a plan is selected." },
];

function featuresFor(plan: ReturnType<typeof useLoaderData<typeof loader>>["plans"][number]) {
  const history = plan.historyDays == null
    ? "Unlimited scan history"
    : `Scan history - ${plan.historyDays >= 365 ? "1 year" : `${plan.historyDays} days`}`;
  const items: { label: string; included: boolean; hl?: boolean }[] = [
    {
      label: plan.qrCodeLimit == null ? "Unlimited dynamic QR codes" : `${plan.qrCodeLimit} dynamic QR codes`,
      included: true,
      hl: plan.qrCodeLimit == null,
    },
    {
      label: plan.campaignLimit == null ? "Unlimited campaign pages" : `${plan.campaignLimit} campaign pages`,
      included: true,
      hl: plan.campaignLimit == null,
    },
    { label: history, included: true, hl: plan.historyDays == null },
    { label: "QR destinations: product, cart, promo code, URL, phone, email, SMS, Wi-Fi and vCard", included: true },
    { label: "QR customization: colors, shapes, logo and label", included: true },
    { label: "PNG, SVG and PDF downloads", included: true },
    { label: "UTM parameters for Google Analytics and Shopify Analytics", included: true },
    { label: "Campaign page editor with product, promo, FAQ, review, video and embedded QR blocks", included: true },
    { label: "Email capture and new lead notifications", included: true },
    { label: "Saved QR design templates", included: true },
    { label: "Scan CSV export", included: true },
  ];

  if (plan.id === "starter") return items;

  items.push(
    { label: "Shopify order attribution", included: plan.attribution, hl: plan.attribution },
    { label: "Conversion reporting by QR code", included: plan.attribution },
  );

  if (plan.id === "pro") {
    items.push(
      { label: "Unlimited QR codes and campaigns", included: true, hl: true },
      { label: "Priority support", included: plan.prioritySupport },
      { label: "Built for advanced marketing teams", included: true },
    );
  } else if (plan.prioritySupport) {
    items.push({ label: "Priority support", included: true });
  }

  return items;
}

export default function PricingPage() {
  const toast = useToast();
  const { plans, currentPlanId, currentCycle, accessStatus, trialDaysLeft, hasActiveSubscription } = useLoaderData<typeof loader>();
  const fetcher = useFetcher<typeof action>();
  const [searchParams, setSearchParams] = useSearchParams();
  const [cycle, setCycle] = useState<"monthly" | "annual">("monthly");
  const [openFaq, setOpenFaq] = useState<string | null>(FAQS[0].q);
  const [confirmCancelOpen, setConfirmCancelOpen] = useState(false);

  // After successful subscription start, redirect to Shopify confirmation page.
  useEffect(() => {
    if (fetcher.state === "idle" && fetcher.data?.ok && fetcher.data.intent === "subscribe" && fetcher.data.confirmationUrl) {
      // Use top-level redirect since the confirmation URL is on Shopify admin.
      window.top!.location.href = fetcher.data.confirmationUrl;
    }
  }, [fetcher.state, fetcher.data]);

  useEffect(() => {
    if (fetcher.state === "idle" && fetcher.data?.ok && fetcher.data.intent === "cancel") {
      setConfirmCancelOpen(false);
      toast({ title: "Subscription cancelled", desc: "Active QR codes and campaigns were paused.", type: "info" });
    }
  }, [fetcher.state, fetcher.data]);

  useEffect(() => {
    if (fetcher.state === "idle" && fetcher.data && !fetcher.data.ok) {
      toast({
        type: "error",
        title: fetcher.data.error === "billing-checkout" ? "Shopify billing blocked" : "Billing action failed",
        desc: "message" in fetcher.data ? fetcher.data.message : "Try again from Shopify admin.",
      });
    }
  }, [fetcher.state, fetcher.data]);

  useEffect(() => {
    if (searchParams.get("billing") === "required") {
      toast({ title: "Subscription required", desc: "The installation trial has ended. Choose a plan to continue.", type: "warning" });
      const next = new URLSearchParams(searchParams);
      next.delete("billing");
      setSearchParams(next, { replace: true });
      return;
    }
    if (searchParams.get("confirmed") === "1") {
      toast({ title: "Payment approved", desc: "Shopify is now syncing your TrackQr subscription." });
      const next = new URLSearchParams(searchParams);
      next.delete("confirmed");
      setSearchParams(next, { replace: true });
    }
  }, []);

  const startCheckout = (planId: string) => {
    const fd = new FormData();
    fd.set("intent", "subscribe");
    fd.set("planId", planId);
    fd.set("cycle", cycle === "annual" ? "ANNUAL" : "MONTHLY");
    const shop = searchParams.get("shop");
    const host = searchParams.get("host");
    if (shop) fd.set("shop", shop);
    if (host) fd.set("host", host);
    fetcher.submit(fd, { method: "post" });
  };

  const cancelActiveSubscription = () => {
    const fd = new FormData();
    fd.set("intent", "cancel");
    const shop = searchParams.get("shop");
    const host = searchParams.get("host");
    if (shop) fd.set("shop", shop);
    if (host) fd.set("host", host);
    fetcher.submit(fd, { method: "post" });
  };

  return (
    <>
      <ConfirmDialog
        open={confirmCancelOpen}
        title="Cancel subscription?"
        description="The active Shopify subscription will be cancelled. Your data stays in TrackQr, but active QR codes and campaigns may be paused if no trial access is available."
        confirmLabel="Cancel subscription"
        cancelLabel="Keep plan"
        tone="danger"
        loading={fetcher.state !== "idle"}
        onClose={() => setConfirmCancelOpen(false)}
        onConfirm={cancelActiveSubscription}
      />

      <div className="page-head">
        <div className="page-head-left" style={{ textAlign: "center", marginInline: "auto", flex: "0 1 720px" }}>
          <div className="page-eyebrow" style={{ marginInline: "auto" }}>
            <Icon name="credit-card" size={11} /> Pricing
          </div>
          <h1 className="page-h1">
            Plans that <span className="em">scale</span> with your scans.
          </h1>
          <div className="page-sub" style={{ marginInline: "auto" }}>
            Create dynamic QR codes, publish campaign pages, and measure sales generated by every scan. Pro features are included during the {INSTALL_TRIAL_DAYS}-day installation trial.
          </div>

          <div className="pricing-cycle">
            <Segmented
              value={cycle}
              onChange={(v) => setCycle(v as "monthly" | "annual")}
              options={[
                { value: "monthly", label: "Monthly" },
                { value: "annual",  label: "Annual" },
              ]}
            />
            <span className={`pricing-cycle-save ${cycle === "annual" ? "on" : ""}`}>
              <Icon name="zap" size={10} />
              Save 20% · 2 months free
            </span>
          </div>
        </div>
      </div>

      <div className="pricing-grid">
        {plans.map(plan => {
          const meta = PLAN_META[plan.id] ?? { icon: "rocket", accent: "blue", tagline: "" };
          const price = cycle === "annual" ? plan.priceAnnual : plan.priceMonthly;
          const selectedCycle = cycle === "annual" ? "ANNUAL" : "MONTHLY";
          const isCurrent = hasActiveSubscription && plan.id === currentPlanId && currentCycle === selectedCycle;
          const isTrialPlan = accessStatus === "trial" && plan.id === currentPlanId;
          const currentIdx = PLAN_ORDER.indexOf(currentPlanId);
          const planIdx    = PLAN_ORDER.indexOf(plan.id);
          const direction  = planIdx > currentIdx ? "up" : planIdx < currentIdx ? "down" : "same";

          return (
            <div
              key={plan.id}
              className={`pricing-card ${meta.featured ? "featured" : ""} ${isCurrent ? "is-current" : ""}`}
              data-accent={meta.accent}
            >
              {meta.badge && !isCurrent && !isTrialPlan && (
                <div className="pricing-badge"><Icon name="sparkles" size={10} />{meta.badge}</div>
              )}
              {isCurrent && (
                <div className="pricing-badge current"><Icon name="circle-check" size={10} />Your {cycle === "annual" ? "annual" : "monthly"} plan</div>
              )}
              {!isCurrent && isTrialPlan && (
                <div className="pricing-badge current"><Icon name="shield" size={10} />Trial Pro · {trialDaysLeft}j</div>
              )}

              <div className="pricing-head">
                <div className="pricing-icon" data-accent={meta.accent}>
                  <Icon name={meta.icon} size={17} />
                </div>
                <div>
                  <div className="pricing-name">{plan.name}</div>
                  <div className="pricing-tag">{meta.tagline}</div>
                </div>
              </div>

              <div className="pricing-price-block">
                <div className="pricing-price">
                  <span className="pricing-currency">$</span>
                  <span className="pricing-amount num">{price}</span>
                  <span className="pricing-per">/mo</span>
                </div>
                <div className="pricing-billed">
                  {cycle === "annual" ? (
                    <>
                      <span className="num strong">${plan.annualTotal.toLocaleString()}</span> billed annually
                      <span className="pricing-strike num">${plan.priceMonthly * 12}</span>
                    </>
                  ) : (
                    <>Billed monthly · ${plan.annualTotal.toLocaleString()}/yr on annual</>
                  )}
                </div>
              </div>

              <Button
                variant={meta.featured && !isCurrent ? "primary" : isCurrent ? "secondary" : "outline"}
                size="lg"
                className="pricing-cta"
                disabled={fetcher.state !== "idle"}
                onClick={() => {
                  if (isCurrent) {
                    toast({ title: "You're on this plan", desc: "Billing is managed in Shopify admin → Settings → Apps.", type: "info" });
                    return;
                  }
                  startCheckout(plan.id);
                }}
                iconRight={isCurrent ? undefined : "arrow-right"}
              >
                {fetcher.state !== "idle"
                  ? "Opening Shopify..."
                  : isCurrent
                    ? `Your ${cycle === "annual" ? "annual" : "monthly"} plan`
                    : direction === "up"
                      ? `Upgrade to ${plan.name} ${cycle === "annual" ? "annual" : "monthly"}`
                      : direction === "down"
                        ? `Switch to ${plan.name} ${cycle === "annual" ? "annual" : "monthly"}`
                        : `Choose ${plan.name} ${cycle === "annual" ? "annual" : "monthly"}`}
              </Button>
              {isCurrent && hasActiveSubscription && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="pricing-cta"
                  disabled={fetcher.state !== "idle"}
                  onClick={() => setConfirmCancelOpen(true)}
                  icon="trash"
                  style={{ marginTop: 8, color: "var(--red-fg)" }}
                >
                  Cancel subscription
                </Button>
              )}

              <div className="pricing-features">
                <div className="pricing-features-label">Included</div>
                <ul>
                  {featuresFor(plan).map((f, i) => (
                    <li key={i} className={f.included ? "" : "off"} data-hl={f.hl ? "true" : "false"}>
                      <Icon name={f.included ? "circle-check" : "x"} size={13} />
                      <span>{f.label}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          );
        })}
      </div>

      <div className="pricing-trust">
        <div><Icon name="shield" size={14} /><span>{INSTALL_TRIAL_DAYS}-day Pro installation trial</span></div>
        <div><Icon name="credit-card" size={14} /><span>Billed through Shopify</span></div>
        <div><Icon name="zap" size={14} /><span>Cancel any time</span></div>
      </div>

      <div className="section">
        <h2 className="section-h">Frequently Asked Questions</h2>
        <Card>
          {FAQS.map((f, i) => (
            <div
              key={f.q}
              style={{
                borderBottom: i === FAQS.length - 1 ? 0 : "1px solid var(--border-soft)",
                padding: "14px 18px",
                cursor: "default",
              }}
              onClick={() => setOpenFaq(openFaq === f.q ? null : f.q)}
            >
              <div className="flex items-center justify-between">
                <div className="strong" style={{ fontSize: 13.5 }}>{f.q}</div>
                <Icon name={openFaq === f.q ? "chevron-up" : "chevron-down"} size={14} style={{ color: "var(--fg-subtle)" }} />
              </div>
              {openFaq === f.q && (
                <div className="text-sm muted mt-2" style={{ maxWidth: 720 }}>{f.a}</div>
              )}
            </div>
          ))}
        </Card>
      </div>

    </>
  );
}
