import type { LoaderFunctionArgs } from "react-router";
import { useLoaderData } from "react-router";
import { CampaignLandingView } from "./c.$slug";
import { pickCampaignLang } from "../lib/campaign-copy";

/**
 * Preview of a campaign page in a new browser tab (drafts included). The tab
 * has no Shopify session, so the link carries a signed, 24-hour token
 * generated by the admin (see campaignPreviewPath in signing.server.ts).
 */
export const loader = async ({ params, request }: LoaderFunctionArgs) => {
  if (!params.id) throw new Response("Missing id", { status: 400 });
  const [{ default: prisma }, { campaignLandingData }, { getBillingAccess, entitlementsForPlan }, { verifyCampaignPreviewToken }] = await Promise.all([
    import("../db.server"),
    import("../lib/campaign-landing.server"),
    import("../lib/plan.server"),
    import("../lib/signing.server"),
  ]);
  const token = new URL(request.url).searchParams.get("token");
  if (!verifyCampaignPreviewToken(params.id, token)) {
    throw new Response("This preview link has expired. Open the preview again from TrackQr.", { status: 404 });
  }
  const campaign = await prisma.campaign.findUnique({
    where: { id: params.id },
    include: { shop: { include: { activeSubscription: { include: { plan: true } } } } },
  });
  if (!campaign) throw new Response("Not found", { status: 404 });
  const access = await getBillingAccess(campaign.shop);
  const entitlements = entitlementsForPlan(access.plan, access.status);
  return campaignLandingData(campaign, {
    isPreview: true,
    customDesign: entitlements.customDesign,
    forcePoweredBy: access.status !== "active",
    pixels: false,
    rewards: entitlements.leadRewards,
    lang: pickCampaignLang(request.headers.get("accept-language")),
  });
};

export const headers = () => ({ "X-Robots-Tag": "noindex", "Cache-Control": "no-store" });

export default function PublicCampaignPreview() {
  const data = useLoaderData<typeof loader>();
  return <CampaignLandingView data={data} />;
}
